/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul.pkg6;

/**
 *
 * @author win 7
 */
public class BASIS extends javax.swing.JFrame {

    /**
     * Creates new form BASIS
     */
    public BASIS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Nama = new javax.swing.JLabel();
        Absen = new javax.swing.JLabel();
        Kelas = new javax.swing.JLabel();
        Jurusan = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        Combo = new javax.swing.JComboBox<>();
        RPL = new javax.swing.JRadioButton();
        TKJ = new javax.swing.JRadioButton();
        Alamat = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Submit = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(null);

        Nama.setForeground(new java.awt.Color(240, 240, 240));
        Nama.setText("NAMA");
        jPanel1.add(Nama);
        Nama.setBounds(10, 20, 50, 14);

        Absen.setForeground(new java.awt.Color(255, 255, 255));
        Absen.setText("ABSEN");
        jPanel1.add(Absen);
        Absen.setBounds(10, 80, 60, 14);

        Kelas.setForeground(new java.awt.Color(255, 255, 255));
        Kelas.setText("KELAS");
        jPanel1.add(Kelas);
        Kelas.setBounds(10, 130, 60, 14);

        Jurusan.setForeground(new java.awt.Color(255, 255, 255));
        Jurusan.setText("JURUSAN");
        jPanel1.add(Jurusan);
        Jurusan.setBounds(10, 190, 70, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(60, 20, 198, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(60, 80, 198, 30);

        Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XRPL 1", "XRPL 2", "XRPL 3", "XRPL 4", "XRPL 5", "XRPL 6", "XRPL 7", " ", "XTKJ 1", "XTKJ 2", "XTKJ 3", "XTKJ 4", "XTKJ 5", "XTKJ 6" }));
        jPanel1.add(Combo);
        Combo.setBounds(102, 129, 140, 30);

        RPL.setText("RPL");
        jPanel1.add(RPL);
        RPL.setBounds(83, 189, 60, 23);

        TKJ.setText("TKJ");
        TKJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKJActionPerformed(evt);
            }
        });
        jPanel1.add(TKJ);
        TKJ.setBounds(181, 189, 70, 23);

        Alamat.setForeground(new java.awt.Color(255, 255, 255));
        Alamat.setText("ALAMAT");
        jPanel1.add(Alamat);
        Alamat.setBounds(10, 280, 70, 14);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(60, 270, 180, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 280, 440);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jLabel1.setText("BIODATA SISWA");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(90, 10, 180, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(210, 0, 290, 440);

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Exit.setText("EXIT");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Submit, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(Submit)
                .addGap(65, 65, 65)
                .addComponent(Exit)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(500, 0, 200, 440);

        setBounds(0, 0, 722, 472);
    }// </editor-fold>//GEN-END:initComponents

    private void TKJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TKJActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
         String nm, abs, jur, almt, kelas = null;
         String Kelas =Combo .getSelectedItem().toString();
         nm = Nama.getText();
         abs = Absen.getText();
         almt = Alamat.getText();  
         //JURUSAN
         if(RPL.isSelected()) {
            jur = "RPL";
            if (Combo.getSelectedItem()=="X RPL 1"){                
            }
              if (Combo.getSelectedItem()=="X RPL 2"){                
            }
                if (Combo.getSelectedItem()=="X RPL 3"){                
            }
                  if (Combo.getSelectedItem()=="X RPL 4"){                
            }
                    if (Combo.getSelectedItem()=="X RPL 5"){                
            }
                      if (Combo.getSelectedItem()=="X RPL 6"){                
            }
                        if (Combo.getSelectedItem()=="X RPL 7"){                
            }
                         }else if(TKJ.isSelected()) {
                             
                             jur="TKJ";
              if (Combo.getSelectedItem()=="X TKJ 1"){                
            }
              if (Combo.getSelectedItem()=="X TKJ 2"){                
        }
              if (Combo.getSelectedItem()=="X TKJ 3"){
                  
              } 
              if (Combo.getSelectedItem()=="X TKJ 4"){                
                  
              }
              if (Combo.getSelectedItem()=="X TKJ 5"){       
                  
              }         
              if (Combo.getSelectedItem()=="X TKJ 6"){                
              }                                      
        }else{ jur = "";}
         
    new FRAME21 (nm, abs, jur, almt, kelas).setVisible(true);
    
    }//GEN-LAST:event_SubmitActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
       dispose();
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BASIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BASIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BASIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BASIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BASIS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Absen;
    private javax.swing.JLabel Alamat;
    private javax.swing.JComboBox<String> Combo;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Jurusan;
    private javax.swing.JLabel Kelas;
    private javax.swing.JLabel Nama;
    private javax.swing.JRadioButton RPL;
    private javax.swing.JButton Submit;
    private javax.swing.JRadioButton TKJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
