package modul.pkg6;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author win 7
 */
public class Kalkulator extends javax.swing.JFrame {
String angka;
double jumlah,angka1,angka2;
int pilih;
    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
        angka="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        hasil = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        persen = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        desimal = new javax.swing.JButton();
        texthasil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KALKULATOR");
        getContentPane().setLayout(null);

        b1.setBackground(new java.awt.Color(0, 255, 204));
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(24, 118, 39, 43);

        b2.setBackground(new java.awt.Color(0, 255, 204));
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(69, 118, 45, 43);

        b3.setBackground(new java.awt.Color(255, 255, 51));
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(124, 118, 40, 43);

        b4.setBackground(new java.awt.Color(255, 255, 51));
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4);
        b4.setBounds(182, 118, 45, 43);

        b5.setBackground(new java.awt.Color(255, 255, 51));
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(237, 118, 45, 43);

        b6.setBackground(new java.awt.Color(255, 153, 153));
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6);
        b6.setBounds(288, 118, 39, 43);

        b7.setBackground(new java.awt.Color(0, 255, 204));
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7);
        b7.setBounds(69, 179, 45, 44);

        b8.setBackground(new java.awt.Color(0, 255, 204));
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8);
        b8.setBounds(124, 179, 40, 44);

        b9.setBackground(new java.awt.Color(255, 255, 51));
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9);
        b9.setBounds(182, 179, 45, 44);

        b0.setBackground(new java.awt.Color(255, 255, 51));
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        getContentPane().add(b0);
        b0.setBounds(237, 179, 49, 44);

        hasil.setBackground(new java.awt.Color(204, 204, 204));
        hasil.setText("=");
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        getContentPane().add(hasil);
        hasil.setBounds(40, 240, 278, 48);

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(10, 380, 55, 40);

        jPanel1.setBackground(new java.awt.Color(102, 255, 153));
        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setText("^");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(350, 230, 40, 30);

        persen.setBackground(new java.awt.Color(102, 102, 255));
        persen.setText("%");
        persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenActionPerformed(evt);
            }
        });
        jPanel1.add(persen);
        persen.setBounds(350, 270, 43, 30);

        clear.setBackground(new java.awt.Color(255, 153, 153));
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(10, 70, 230, 40);

        kurang.setBackground(new java.awt.Color(102, 102, 255));
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        jPanel1.add(kurang);
        kurang.setBounds(350, 310, 36, 31);

        tambah.setBackground(new java.awt.Color(102, 102, 255));
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel1.add(tambah);
        tambah.setBounds(350, 190, 41, 31);

        kali.setBackground(new java.awt.Color(102, 102, 255));
        kali.setText("*");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        jPanel1.add(kali);
        kali.setBounds(350, 150, 39, 31);

        bagi.setBackground(new java.awt.Color(102, 51, 255));
        bagi.setText("/");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        jPanel1.add(bagi);
        bagi.setBounds(350, 110, 36, 31);

        jButton4.setBackground(new java.awt.Color(255, 153, 153));
        jButton4.setText("   <----");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(250, 80, 65, 23);

        desimal.setBackground(new java.awt.Color(102, 102, 255));
        desimal.setText(".");
        desimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desimalActionPerformed(evt);
            }
        });
        jPanel1.add(desimal);
        desimal.setBounds(350, 70, 40, 30);

        texthasil.setBackground(new java.awt.Color(51, 255, 255));
        texthasil.setText("0");
        texthasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texthasilActionPerformed(evt);
            }
        });
        jPanel1.add(texthasil);
        texthasil.setBounds(10, 10, 380, 50);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 12)); // NOI18N
        jLabel1.setText("MEMPERMUDAH URUSAN MATEMATIKA ANDA :V");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 310, 323, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 440);

        setBounds(0, 0, 415, 475);
    }// </editor-fold>//GEN-END:initComponents

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
     angka += "4";
texthasil.setText(angka);
    }//GEN-LAST:event_b4ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
       angka += "7";
texthasil.setText(angka);
    }//GEN-LAST:event_b7ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
      angka += "9";
texthasil.setText(angka);
    }//GEN-LAST:event_b9ActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
      angka1=Double.parseDouble(angka);
texthasil.setText("+");
angka="";
pilih=1;

    }//GEN-LAST:event_tambahActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
      angka1=Double.parseDouble(angka);
texthasil.setText("-");
angka="";
pilih=2;

    }//GEN-LAST:event_kurangActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        angka1=Double.parseDouble(angka);
texthasil.setText("*");
angka="";
pilih=3;
    }//GEN-LAST:event_kaliActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
     angka1=Double.parseDouble(angka);
texthasil.setText("/");
texthasil.setText("");
angka="";
pilih=4;
    }//GEN-LAST:event_bagiActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
switch(pilih){
     case 1:
         angka2 = Double.parseDouble(angka);
         jumlah = angka1 + angka2;
         angka = Double.toString(jumlah);
         texthasil.setText(angka);
         break;
        
     case 2:
         angka2 = Double.parseDouble(angka);
         jumlah = angka1 - angka2;
         angka = Double.toString(jumlah);
         texthasil.setText(angka);
         break;
    
     case 3:
         angka2 = Double.parseDouble(angka);
         jumlah = angka1 * angka2;
         angka = Double.toString(jumlah);
         texthasil.setText(angka);
         break;
        
     case 4:
         angka2 = Double.parseDouble(angka);
         jumlah = angka1 / angka2;
         angka = Double.toString(jumlah);
         texthasil.setText(angka);
         
         
           case 6:
         angka2 = Double.parseDouble(angka);
         jumlah = Math.pow(angka1,angka2);
         angka = Double.toString(jumlah);
         texthasil.setText(angka);
         
         break;
     default:
     break;
        }
                                
    }//GEN-LAST:event_hasilActionPerformed

    private void texthasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texthasilActionPerformed

    }//GEN-LAST:event_texthasilActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
    texthasil.setText("");
angka1=0.0;
angka2=0.0;
jumlah=0.0;
angka="";
    }//GEN-LAST:event_clearActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        angka += "1";
texthasil.setText(angka);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
       angka += "2";
texthasil.setText(angka);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
angka += "3";
texthasil.setText(angka);
    }//GEN-LAST:event_b3ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
     angka += "5";
texthasil.setText(angka);
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
       angka += "6";
texthasil.setText(angka);
    }//GEN-LAST:event_b6ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
    angka += "8";
texthasil.setText(angka);
    }//GEN-LAST:event_b8ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        angka += "0";
texthasil.setText(angka);
    }//GEN-LAST:event_b0ActionPerformed

    private void persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenActionPerformed
 angka1=Double.parseDouble(angka);
 jumlah=angka1/100;
texthasil.setText(""+jumlah);
angka="";
    }//GEN-LAST:event_persenActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
      dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       angka1=Double.parseDouble(angka);
texthasil.setText("^");
angka="";
pilih=6;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       angka = angka.substring(0, angka.length()-1);
       texthasil.setText(angka);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void desimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desimalActionPerformed
      angka +=".";
      texthasil.setText(angka);
    }//GEN-LAST:event_desimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bagi;
    private javax.swing.JButton clear;
    private javax.swing.JButton desimal;
    private javax.swing.JButton exit;
    private javax.swing.JButton hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kali;
    private javax.swing.JButton kurang;
    private javax.swing.JButton persen;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField texthasil;
    // End of variables declaration//GEN-END:variables
}
