/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul.pkg6;

/**
 *
 * @author win 7
 */
public class Latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan1
     */
    public Latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Biodata = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Absen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Kelas = new javax.swing.JComboBox<>();
        RPL = new javax.swing.JRadioButton();
        TKJ = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Send = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Biodata.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        Biodata.setText("Biodata");
        getContentPane().add(Biodata);
        Biodata.setBounds(150, 10, 100, 14);

        Nama.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        Nama.setText("Nama :");
        getContentPane().add(Nama);
        Nama.setBounds(30, 50, 50, 19);

        Absen.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        Absen.setText("Absen : ");
        getContentPane().add(Absen);
        Absen.setBounds(30, 90, 50, 19);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel1.setText("Kelas : ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 130, 50, 19);

        Kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X RPL 1", "X RPL 2", "X RPL 3", "X RPL 3", "X RPL 4", "X RPL 5", "X RPL 6", "X RPL 7", " ", "X TKJ 1", "X TKJ 2", "X TKJ 3", "X TKJ 4", "X TKJ 5", "X TKJ 6", " " }));
        getContentPane().add(Kelas);
        Kelas.setBounds(90, 130, 70, 20);

        RPL.setText("RPL");
        getContentPane().add(RPL);
        RPL.setBounds(90, 180, 50, 23);

        TKJ.setText("TKJ");
        getContentPane().add(TKJ);
        TKJ.setBounds(150, 180, 43, 23);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        jLabel2.setText("Jurusan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 180, 50, 19);

        Alamat.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        Alamat.setText("Alamat : ");
        getContentPane().add(Alamat);
        Alamat.setBounds(30, 220, 60, 19);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(80, 50, 100, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(80, 90, 110, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(90, 220, 100, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\win 7\\Pictures\\download.png")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 20, 210, 290);

        Send.setText("Send");
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });
        getContentPane().add(Send);
        Send.setBounds(10, 260, 57, 23);

        Exit.setText("Exit");
        getContentPane().add(Exit);
        Exit.setBounds(100, 260, 51, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
     String nama =Nama.getText();
     String absen=Absen.getText();
     String kelas=Kelas.getSelectedItem().toString();
     String jurusan =" ";
     String alamat=Alamat.getText();
     
       if(RPL.isSelected()) {
            jurusan = "RPL";
            if (Kelas.getSelectedItem()=="X RPL 1"){                
            }
              if (Kelas.getSelectedItem()=="X RPL 2"){                
            }
                if (Kelas.getSelectedItem()=="X RPL 3"){                
            }
                  if (Kelas.getSelectedItem()=="X RPL 4"){                
            }
                    if (Kelas.getSelectedItem()=="X RPL 5"){                
            }
                      if (Kelas.getSelectedItem()=="X RPL 6"){                
            }
                        if (Kelas.getSelectedItem()=="X RPL 7"){                
            }
                         }else if(TKJ.isSelected()) {
                             
                             jurusan="TKJ";
              if (Kelas.getSelectedItem()=="X TKJ 1"){                
            }
              if (Kelas.getSelectedItem()=="X TKJ 2"){                
        }
              if (Kelas.getSelectedItem()=="X TKJ 3"){
                  
              } 
              if (Kelas.getSelectedItem()=="X TKJ 4"){                
                  
              }
              if (Kelas.getSelectedItem()=="X TKJ 5"){       
                  
              }         
              if (Kelas.getSelectedItem()=="X TKJ 6"){                
              }                                      
        }else{ jurusan = "";}
       new Frame2(nama, absen, kelas, jurusan,alamat).setVisible(true);
    }//GEN-LAST:event_SendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Absen;
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Biodata;
    private javax.swing.JButton Exit;
    private javax.swing.JComboBox<String> Kelas;
    private javax.swing.JLabel Nama;
    private javax.swing.JRadioButton RPL;
    private javax.swing.JButton Send;
    private javax.swing.JRadioButton TKJ;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
