/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul.pkg6;

import javax.swing.JOptionPane;

/**
 *
 * @author win 7
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Panjang = new javax.swing.JTextField();
        Lebar = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Sisi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Jari = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel2.setText("Masukkan Panjang :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 11, 110, 30);

        jLabel3.setText("Masukkan Lebar : ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 50, 110, 30);

        jLabel4.setText("Masukkan Tinggi :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 90, 110, 30);

        Panjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanjangActionPerformed(evt);
            }
        });
        jPanel2.add(Panjang);
        Panjang.setBounds(130, 10, 130, 30);
        jPanel2.add(Lebar);
        Lebar.setBounds(130, 50, 130, 30);

        Tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinggiActionPerformed(evt);
            }
        });
        jPanel2.add(Tinggi);
        Tinggi.setBounds(130, 90, 130, 30);

        jLabel1.setText("CM");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(300, 20, 40, 20);

        jLabel5.setText("CM");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(300, 60, 50, 20);

        jLabel6.setText("CM");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(300, 100, 60, 20);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(130, 160, 100, 23);

        jTabbedPane1.addTab("Balok", jPanel2);

        jPanel3.setLayout(null);

        jLabel7.setText("Masukkan Panjang Sisi : ");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 42, 130, 40);

        Sisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SisiActionPerformed(evt);
            }
        });
        jPanel3.add(Sisi);
        Sisi.setBounds(10, 100, 170, 30);

        jLabel8.setText("CM");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(200, 110, 30, 14);

        jButton2.setText("Volume");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(140, 160, 100, 23);

        jTabbedPane1.addTab("Kubus", jPanel3);

        jPanel4.setLayout(null);

        jLabel9.setText("Masukkan Panjang Jari - Jari : ");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 30, 230, 40);
        jPanel4.add(Jari);
        Jari.setBounds(20, 80, 200, 40);

        jLabel10.setText("CM");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(250, 100, 30, 14);

        jButton3.setText("Volume");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(120, 140, 150, 30);

        jTabbedPane1.addTab("Bola", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 41, 380, 248);

        jLabel11.setText("PROGRAM PENCARI VOLUME BANGUN RUANG");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(80, 10, 270, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanjangActionPerformed

    private void TinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TinggiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     int panjang, lebar, tinggi;
     panjang=Integer.parseInt(Panjang.getText());
     lebar=Integer.parseInt(Lebar.getText());
     tinggi=Integer.parseInt(Tinggi.getText());
     int hasil=panjang*lebar*tinggi;
     try{
         JOptionPane.showMessageDialog(null, "Volume Balok Adalah : "+hasil,"Luas : ",JOptionPane.INFORMATION_MESSAGE);
         
     }catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Error"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     float jari;
     jari=Integer.parseInt(Jari.getText());
     float hasil1=(float)(4/3*3.14*jari*jari*jari);
     try{
         
         JOptionPane.showMessageDialog(null, "Luas Permukaan Bola : "+hasil1,"Luas : ",JOptionPane.INFORMATION_MESSAGE);
         
     }catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Error"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
     }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     int sisi;
     sisi=Integer.parseInt(Sisi.getText());
     int hasil=sisi*sisi*sisi;
     try{
         JOptionPane.showMessageDialog(null, "Luas Permukaan Kubus: "+hasil,"Luas : ",JOptionPane.INFORMATION_MESSAGE);
         
     }catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Error"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jari;
    private javax.swing.JTextField Lebar;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField Sisi;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
