/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul.pkg6;

/**
 *
 * @author win 7
 */
public class Praktek1 extends javax.swing.JFrame {

    /**
     * Creates new form Praktek1
     */
    public Praktek1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jTextberat = new javax.swing.JTextField();
        jTexttinggi = new javax.swing.JTextField();
        jRadioLaki = new javax.swing.JRadioButton();
        jRadioPerempuan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasilbbideal = new javax.swing.JTextPane();
        hitung = new javax.swing.JButton();
        ulang = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hasilanalisakesehatan = new javax.swing.JTextPane();
        saran = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 207, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("CEK KESEHATAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 150, 17);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 70, 14);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Berat Badan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 90, 100, 14);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tinggi Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 110, 14);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 160, 90, 14);

        Nama.setForeground(new java.awt.Color(102, 51, 255));
        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(90, 40, 120, 30);

        jTextberat.setForeground(new java.awt.Color(102, 51, 255));
        jTextberat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextberatActionPerformed(evt);
            }
        });
        getContentPane().add(jTextberat);
        jTextberat.setBounds(90, 80, 120, 30);

        jTexttinggi.setForeground(new java.awt.Color(102, 51, 255));
        jTexttinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexttinggiActionPerformed(evt);
            }
        });
        getContentPane().add(jTexttinggi);
        jTexttinggi.setBounds(90, 120, 120, 30);

        buttonGroup1.add(jRadioLaki);
        jRadioLaki.setForeground(new java.awt.Color(102, 51, 255));
        jRadioLaki.setText("Laki Laki");
        jRadioLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioLakiActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioLaki);
        jRadioLaki.setBounds(90, 160, 120, 23);

        buttonGroup1.add(jRadioPerempuan);
        jRadioPerempuan.setForeground(new java.awt.Color(102, 51, 255));
        jRadioPerempuan.setText("Perempuan");
        jRadioPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioPerempuanActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioPerempuan);
        jRadioPerempuan.setBounds(220, 160, 150, 23);

        jScrollPane1.setForeground(new java.awt.Color(51, 0, 255));
        jScrollPane1.setViewportView(hasilbbideal);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 250, 210, 30);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(13, 190, 110, 30);

        ulang.setText("Ulang");
        ulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangActionPerformed(evt);
            }
        });
        getContentPane().add(ulang);
        ulang.setBounds(129, 190, 90, 30);

        jLabel6.setForeground(new java.awt.Color(51, 0, 255));
        jLabel6.setText("Hasil analisa kesehatan :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 310, 290, 14);

        jScrollPane2.setForeground(new java.awt.Color(51, 0, 255));
        jScrollPane2.setViewportView(hasilanalisakesehatan);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(160, 300, 210, 30);

        saran.setForeground(new java.awt.Color(51, 0, 255));
        saran.setText("Saran");
        getContentPane().add(saran);
        saran.setBounds(20, 350, 310, 70);

        jLabel7.setForeground(new java.awt.Color(51, 0, 255));
        jLabel7.setText("Berat badan ideal anda :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 260, 220, 14);

        keluar.setText("Keluar");
        getContentPane().add(keluar);
        keluar.setBounds(223, 190, 100, 30);

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 200, 220);

        jPanel4.setBackground(new java.awt.Color(51, 204, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 220, 200, 240);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(200, 0, 200, 220);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(200, 220, 200, 240);

        setBounds(0, 0, 415, 498);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void jRadioLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioLakiActionPerformed

    private void jTextberatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextberatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextberatActionPerformed

    private void jTexttinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexttinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexttinggiActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
  
        double t, b, h = 0;
   
   
   t = Double.valueOf(jTexttinggi.getText());
   b = Double.valueOf(jTextberat.getText());
   String nm = Nama.getText();
   
   if(jRadioLaki.isSelected()){
       
   h = (t-100);
   
    }else if (jRadioPerempuan.isSelected()){
        
            h = (t - 104);
    }  
            
    String temp = Double.toString(h);
    
    if(h>b){
    hasilbbideal.setText(temp);
    hasilanalisakesehatan.setText("Maaf"+ nm+ "Anda kekurangan Berat Badan");
    saran.setText("Makan makanan yang bergizi");
    
    }else if (h<b){
          hasilbbideal.setText(temp);
    hasilanalisakesehatan.setText("Maaf"+ nm+ "Anda kelebihan Berat Badan");
    saran.setText("Olahraga teratur");
    
    }else{
        hasilbbideal.setText(temp);
        hasilanalisakesehatan.setText("Berat Badan anda sudah ideal");
        saran.setText("MANTAAAPPPPPZZZZ");
                
        
    }
    
    }//GEN-LAST:event_hitungActionPerformed

    private void ulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangActionPerformed
        Nama.setText(" ");
   jTextberat.setText("");
   jTexttinggi.setText(" ");
   hasilbbideal.setText(" ");
   hasilanalisakesehatan.setText(" ");
   saran.setText(" ");   
    }//GEN-LAST:event_ulangActionPerformed

    private void jRadioPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioPerempuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Praktek1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Praktek1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Praktek1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Praktek1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Praktek1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nama;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextPane hasilanalisakesehatan;
    private javax.swing.JTextPane hasilbbideal;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioLaki;
    private javax.swing.JRadioButton jRadioPerempuan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextberat;
    private javax.swing.JTextField jTexttinggi;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField saran;
    private javax.swing.JButton ulang;
    // End of variables declaration//GEN-END:variables
}
