/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modul6;

/**
 *
 * @author win 7
 */
public class Kuis1 extends javax.swing.JFrame {
    
    /**
     * Creates new form Kuis1
     */
    public Kuis1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Absen = new javax.swing.JTextField();
        Mapel = new javax.swing.JTextField();
        Nilai = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("PENILAIN SISWA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(142, 11, 130, 20);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 60, 14);

        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 60, 14);

        jLabel4.setText("Mapel");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 60, 14);

        jLabel5.setText("Nilai");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 170, 60, 14);
        getContentPane().add(Nama);
        Nama.setBounds(100, 40, 150, 30);
        getContentPane().add(Absen);
        Absen.setBounds(100, 80, 150, 30);
        getContentPane().add(Mapel);
        Mapel.setBounds(100, 120, 150, 30);
        getContentPane().add(Nilai);
        Nilai.setBounds(100, 160, 150, 30);

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 200, 90, 30);

        text.setColumns(20);
        text.setRows(5);
        jScrollPane1.setViewportView(text);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 240, 340, 110);

        setBounds(0, 0, 511, 392);
    }// </editor-fold>//GEN-END:initComponents
  
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String nama = Nama.getText();
      String absen = Absen.getText();
      String mapel=Mapel.getText();
      int nilai=Integer.parseInt(Nilai.getText());
      String hasil = "";     
      
     if( nilai< 50) 
         hasil="Perbaiki";

          if (nilai > 50)
         hasil="Kurang";
         
         if(nilai > 60){
             hasil="Maksimalkan";
             
             if(nilai >70){
                 hasil="Semangatt terus";
                 
                 if (nilai> 80 ){
                     hasil="Alhamdulillah";
                     
                   
                     
                     
                 }
             }
         }
    
       text.setText("Nama Siswa : "+nama+"\n"+"Absen :"+absen+"\n"+"Mapel :"+mapel+"\n"+"Nilai : "+nilai+"\n"+"Keteragan : "+hasil);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     
        //</editor-fold>

    /**
     *
     * @param args
     */
     public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis1().setVisible(true);
            }
        });
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JTextField Mapel;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nilai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}

