/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modul6;

/**
 *
 * @author win 7
 */
public class Kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis2
     */
    public Kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Barang1 = new javax.swing.JTextField();
        Barang2 = new javax.swing.JTextField();
        try {
            Barang3 =(javax.swing.JTextField)java.beans.Beans.instantiate(getClass().getClassLoader(), "Modul6.Kuis2_Barang3");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        Barang4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Diskon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("PEMBAYARAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 80, 20);

        jLabel2.setText("Harga barang 1 :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 40, 120, 20);

        jLabel3.setText("Harga barang 2 :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 90, 120, 14);

        jLabel4.setText("Harga barang 3 :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 130, 110, 14);

        jLabel5.setText("Harga barang 4 :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 170, 110, 14);
        getContentPane().add(Barang1);
        Barang1.setBounds(180, 40, 110, 30);
        getContentPane().add(Barang2);
        Barang2.setBounds(180, 80, 110, 30);
        getContentPane().add(Barang3);
        Barang3.setBounds(180, 130, 110, 30);
        getContentPane().add(Barang4);
        Barang4.setBounds(180, 170, 110, 30);

        jLabel6.setText("Diskon :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 220, 90, 20);
        getContentPane().add(Diskon);
        Diskon.setBounds(140, 220, 110, 40);

        Text.setColumns(20);
        Text.setRows(5);
        jScrollPane1.setViewportView(Text);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 316, 340, 110);

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(15, 280, 100, 23);

        jButton2.setText("Hapus");
        getContentPane().add(jButton2);
        jButton2.setBounds(133, 280, 100, 23);

        jButton4.setText("Keluar");
        getContentPane().add(jButton4);
        jButton4.setBounds(250, 280, 90, 23);

        setBounds(0, 0, 416, 477);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String hargabarang1=Barang1.getText();
        String hargabarang2=Barang2.getText();
         String hargabarang3=Barang3.getText();
        String hargabarang4=Barang4.getText();
        //Proses
        int bil1 = Integer.parseInt(Barang1.getText());
      int bil2 = Integer.parseInt(Barang2.getText());
         int bil3 = Integer.parseInt(Barang3.getText());
            int bil4= Integer.parseInt(Barang4.getText());
        int hasil = bil1+bil2+bil3+bil4;
        int diskon=Integer.parseInt(Diskon.getText());
        
         Text.setText("Harga Barang 1 : " + bil1 + "\n" + "Harga Barang 2 : "+ bil2 + "\n" + "Harga Barang 3  : " +bil3+ "\n" + "Harga Barang 4 :  " + bil4 +"\n"+"Diskon : "+Diskon+  
                 "\n" +"Total Pembelian : "+hasil+"Diskon : "+diskon);
       int jumlah;  
       jumlah=hasil*(100-diskon)/100;
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Barang1;
    private javax.swing.JTextField Barang2;
    private javax.swing.JTextField Barang3;
    private javax.swing.JTextField Barang4;
    private javax.swing.JTextField Diskon;
    private javax.swing.JTextArea Text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
