/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modul6;

/**
 *
 * @author win 7
 */
public class Latian02 extends javax.swing.JFrame {

    /**
     * Creates new form Latian02
     */
    public Latian02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PilihanJurusan = new javax.swing.ButtonGroup();
        Biodata = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        lblAbsen = new javax.swing.JLabel();
        Jurusan = new javax.swing.JLabel();
        Hasil = new javax.swing.JLabel();
        TKJ = new javax.swing.JRadioButton();
        RPL = new javax.swing.JRadioButton();
        Hobi = new javax.swing.JLabel();
        Futsal = new javax.swing.JCheckBox();
        Silat = new javax.swing.JCheckBox();
        Bola = new javax.swing.JCheckBox();
        Renang = new javax.swing.JCheckBox();
        Submit = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        Name = new javax.swing.JTextField();
        Absen = new javax.swing.JTextField();
        txaHasil = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Biodata.setText("Biodata");

        Nama.setText("Nama ");

        lblAbsen.setText("Absen ");

        Jurusan.setText("Jurusan ");

        Hasil.setText("Hasil ");

        TKJ.setText("TKJ");
        TKJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKJActionPerformed(evt);
            }
        });

        RPL.setText("RPL");
        RPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPLActionPerformed(evt);
            }
        });

        Hobi.setText("Hobi ");

        Futsal.setText("Futsal");

        Silat.setText("Pencak Silat");

        Bola.setText("Sepak Bola");

        Renang.setText("Renang");
        Renang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenangActionPerformed(evt);
            }
        });

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Remove.setText("Remove");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        Absen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbsenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(Biodata, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Nama)
                .addGap(20, 20, 20)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Absen, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TKJ)
                .addGap(7, 7, 7)
                .addComponent(RPL, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Hobi))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Futsal)
                .addGap(115, 115, 115)
                .addComponent(Bola))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Silat)
                .addGap(87, 87, 87)
                .addComponent(Renang))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Submit)
                .addGap(45, 45, 45)
                .addComponent(Remove)
                .addGap(39, 39, 39)
                .addComponent(exit))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Hasil))
            .addComponent(txaHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(Biodata)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nama)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAbsen)
                    .addComponent(Absen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jurusan)
                    .addComponent(TKJ)
                    .addComponent(RPL))
                .addGap(7, 7, 7)
                .addComponent(Hobi)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Futsal)
                    .addComponent(Bola))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Silat)
                    .addComponent(Renang))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Submit)
                    .addComponent(Remove)
                    .addComponent(exit))
                .addGap(7, 7, 7)
                .addComponent(Hasil)
                .addGap(10, 10, 10)
                .addComponent(txaHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPLActionPerformed
     
    }//GEN-LAST:event_RPLActionPerformed

    private void RenangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RenangActionPerformed

    private void TKJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKJActionPerformed
       
    }//GEN-LAST:event_TKJActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed


    }//GEN-LAST:event_NameActionPerformed

    private void AbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbsenActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
      String nama = Name.getText();
      String absen = Absen.getText();
      String Jurusan;
      String Hobi =(" ");
      
      if (RPL.isSelected())
          Jurusan = "RPL";
      
      else if (TKJ.isSelected())
          Jurusan = "TKJ";
      else
          Jurusan = "";
      
      if(Futsal.isSelected())
          Hobi+=Futsal.getText() +", ";
      if(Silat.isSelected())
          Hobi+=Silat.getText() +", ";
      if(Bola.isSelected())
          Hobi+=Bola.getText() + ", ";
      if(Renang.isSelected())
          Hobi+=Renang.getText()+ ", ";
      
     txaHasil.setText("Nama : "+nama+"\nAbsen : "+absen+"\nJurusan : "+Jurusan+"\nHobi : " +Hobi);
          
          
          
    }//GEN-LAST:event_SubmitActionPerformed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
      Nama.setText(" ");
      Absen.setText(" ");
      Hobi.setText(" ");
      Jurusan.setText(" ");
      Hasil.setText(" ");
      Futsal.setSelected(false);
      Silat.setSelected(false);
      Bola.setSelected(false);
      Renang.setSelected(false);
    }//GEN-LAST:event_RemoveActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
     System.exit (0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latian02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latian02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latian02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latian02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latian02().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JLabel Biodata;
    private javax.swing.JCheckBox Bola;
    private javax.swing.JCheckBox Futsal;
    private javax.swing.JLabel Hasil;
    private javax.swing.JLabel Hobi;
    private javax.swing.JLabel Jurusan;
    private javax.swing.JLabel Nama;
    private javax.swing.JTextField Name;
    private javax.swing.ButtonGroup PilihanJurusan;
    private javax.swing.JRadioButton RPL;
    private javax.swing.JButton Remove;
    private javax.swing.JCheckBox Renang;
    private javax.swing.JCheckBox Silat;
    private javax.swing.JButton Submit;
    private javax.swing.JRadioButton TKJ;
    private javax.swing.JButton exit;
    private javax.swing.JLabel lblAbsen;
    private java.awt.TextArea txaHasil;
    // End of variables declaration//GEN-END:variables
}
